### ISSUE TITLE
Properly label mtest in CMake to allow external use

### ISSUE THREAD

**Issue by soupglasses** [MortenSchou/mtest#2]
Allow mtest to be properly labelled in CMake with project exports to allow distribution and external use.

This would allow one to use `find_package(mtest)` and (possibly?) `pkg-config` with mtest such that a package manager can handle the install/update of mtest as a project.

This is compared to the current methods of installing mtest using `FetchContent` or git submodules. Neither allows an external management of dependencies, for example in packaging up C projects.

An example layout for this would be like:
- The `include` folder gets exported into a `include` or `include/mtest`.
- The `cmake` folder gets exported into a `share/cmake` or `share/cmake/mtest` folder.
- Set up the relevant package descriptions for versioning. (F.x. `COMPATIBILITY AnyNewerVersion`).

I have personally been looking at [how googletest does this](https://github.com/google/googletest/blob/main/googletest/CMakeLists.txt), but my skills with CMake is sadly not sufficient for creating a PR with these changes applied.

**Comment by soupglasses** [comment]
I will be continuing to work on this, but it may require some time.

**Comment by MortenSchou** [comment]
I originally attempted this without success, so I decided to keep it simple and just use `FetchContent`. 
Good luck, here is a useful reference: https://cmake.org/cmake/help/latest/guide/importing-exporting/index.html#exporting-targets

**Comment by soupglasses** [comment]
![chuckles-im-in-danger](https://github.com/MortenSchou/mtest/assets/20756843/2177ea47-efd4-4b8b-b24c-a8bc3f205473)
