### ISSUE TITLE
`discover_tests` only discovers single target

### ISSUE THREAD

**Issue by soupglasses** [MortenSchou/mtest#5]
Currently, `discover_tests` only works for a single target, when it sounds like it should support multiple targets due to the plural `tests`.

Using multiple lines of `discover_tests` per target seems to work correctly, and exposes CTest to the tests.

An idea I have to solve this would be:
1. Rename current `discover_tests` to `discover_test` to signify its single target nature.
2. Create a new function `discover_tests` that wraps `discover_test` with any amount of targets.

Alternatively, one could also make the current `discover_tests` support multiple targets without an intermediary function, sadly my CMake skills are lacking to know how to to that.

**Comment by MortenSchou** [comment]
There can be multiple `tests` in a single test target. But fair, we might as well support multiple targets. 
Turns out to be easy: Just add a foreach loop in the CMake file: #6
